### ISSUE TITLE
Show history

### ISSUE THREAD

**Issue by JDrit** [TalCohen/CSHWebPacket#5]
I would love to see the names of the people that I have and have not signed for a given year. As soon as a person passes their 2 week mark, I can no longer see if I signed someone or not. I do not like having to keep a copy for my own record of who I have and have not signed.

**Comment by TalCohen** [comment]
This is a potential feature of Pvals (Matt's project). Packet is more so the client used for actually signing packets, whereas Pvals is more for viewing all long-term data.
