### ISSUE TITLE
Add checkmark for packets that I have signed

### ISSUE THREAD

**Issue by rswiernik** [TalCohen/CSHWebPacket#6]
The page /freshmen shows how many signatures each of the freshmen have. This is super useful, however when looking through which freshmen have the most signatures, it'd be useful to see which of those packets I have signed. It'd be cool if you could add some sort of differentiator on that page to show which I've signed.

**Comment by TalCohen** [comment]
Sorry, just saw this now. If Pvals doesn't replace Packet by the start of next year, I'll look into implementing this in some way by then.
