### ISSUE TITLE
Freshmen Signing Own Packets

### ISSUE THREAD

**Issue by RamZallan** [TalCohen/CSHWebPacket#7]
Currently, freshmen can sign their own packets. It looks like that may be able to be fixed in [/app/controllers/signatures_controller.rb](https://github.com/TalCohen/CSHWebPacket/blob/master/app/controllers/signatures_controller.rb#L13). The linked line checks if the user has selected a freshman's packet, and is signed in as a freshman, but not whether or not the freshman signed in is selecting their own packet. This can add artificial signatures to their packet. You can see in [this screenshot](http://i.imgur.com/4ROAFEk.png) that I've been able to sign my own packet. 

###### (Quest done, Liam)

**Comment by TalCohen** [comment]
Working as intended.
